
name: Build and Deploy

on:
  push:
    branches: [ feature/#212-github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.18.4]

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm test and npm run build
        run: |
          yarn install
          #npm run test
          npm run build-production

      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.4
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: quantified-self-dopanik
          TARGET_BRANCH: feature/#212-github-actions
